import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaVideo } from "react-icons/fa";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ `  flex flex-col  h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full h-10 flex items-center px-20 bg-white">
          <FaVideo style={{
            color:'#7B7AE7'
          }}></FaVideo>
          <p className="font-sans font-bold text-sm mx-2">Video Lens</p>
        </header>
       
        {children}
      
      </body>
    </html>
  );
}
